### ISSUE TITLE
Spaces in job stats job_id field are not handled

### ISSUE THREAD

**Issue by morrone** [LLNL/ldms-plugins-llnl#10]
>Did you consider spaces in jobids when you parse them? It looks like the sampler will only get the part before the first space in the actual job id, and this may cause some create failure when multiple jobs have the same "first part".

The code is just using "%s" in sscanf, which stops at white space. That parsing will need to be improved.

**Comment by morrone** [comment]
@wooloo1121, please try ldms-plugin-llnl release 1.13. I changed the sscanf to read all characters up until newline rather than just using "%s". That should include white space in the jobid.

**Comment by wooloo1121** [comment]
@morrone Sorry for the late reply, I was on a vacation. And thank you for the changes, it works well now, we do not see the failure any more.

**Comment by morrone** [comment]
No problem! Thank you for the feedback!
