### ISSUE TITLE
instructions on installing this plugin

### ISSUE THREAD

**Issue by wooloo1121** [LLNL/ldms-plugins-llnl#3]
Hi,

We want to use this plugin on our hpc cluster, but don't find any instructions on how to install this separate plugin. We tried compiling the code and copying over the lib files, but it still doesn't seem to work with ldms (v4.3.4 beta) since we could not get data with ldms_ls. Can you provide some instructions on installing? 

ps. there are some header files missing when compiling so we have to copy the ones from ldms (/opt/ovis/include) over.

Thank you and look forward to your reply.

**Comment by morrone** [comment]
Yes, I didn't have support for alternative install locations of ldms (/opt/ovis) in our configure scripts.

If you want to test with the master branch, I just added a commit that may allow that to work. You would build with:

```
./bootstrap
./configure --prefix=/opt/ovis --with-libldms-prefix=/opt/ovis
make
make install
```

**Comment by wooloo1121** [comment]
@morrone Thank you for the help, we really appreciate it. But it still doesn't seem to work so we turn to install ldms by default path. It works! :) And do the job stats plugins support lustre 2.12?

**Comment by morrone** [comment]
@wooloo1121 ,Yes, it is the intent that it work with 2.12.

**Comment by wooloo1121** [comment]
Hi @morrone, sorry for posting here again, but we are deploying this job stats plugin on production environment and it would be a lot better if we could have alternative installation location working. With master branch and  " ./configure --prefix=/opt/ovis --with-libldms-prefix=/opt/ovis ", it still says some header files not found (the header files are indeed under /opt/ovis/include/ldms). Could you help look a bit more into it? Thank you so much.
