### ISSUE TITLE
could not collect data from 1.11 installed on alternative path with ldms_ls

### ISSUE THREAD

**Issue by wooloo1121** [LLNL/ldms-plugins-llnl#8]
Hi,

Thank you very much for the effort to enable the samplers to be installed on alternative path. We tried with 1.11, it worked with the installation but no data showed up with ldms_ls, therefore the aggregator could not get any data either. 

Hence, we copied the lib files installed by default path over to alternative path, and when we started the service with systemctl，the parsing problem #4 showed again. 

Thank you again for your effort and look forward to your reply.

**Comment by morrone** [comment]
Could you please provide your full configure command? And how did you install the plugins that resulted from that build? It is unclear what you mean by no data showing up in ldms_ls. If the plugins were unable to load, I would expect the ldmsd to throw an error at plugin load time. What did you see in the ldmsd logs at plugin load time?  Perhaps turn on full debugging with "-v DEBUG" when you start the ldmsd sampler daemon.

**Comment by wooloo1121** [comment]
@morrone There is no error at plugin load time.  The following logs may be helpful:
Sun Dec 13 20:17:14 2020: DEBUG     : msg_no 14 flags 3 rec_len 28 rsp_err 0
Sun Dec 13 20:17:14 2020: DEBUG     : msg_no 15 flags 3 rec_len 28 rsp_err 0
Sun Dec 13 20:17:14 2020: DEBUG     : Checking for llnl_lustre_client in /opt/ovis/lib/ovis-ldms
Sun Dec 13 20:17:14 2020: DEBUG     : lustre_client get_plugin() called
Sun Dec 13 20:17:14 2020: DEBUG     : msg_no 16 flags 3 rec_len 28 rsp_err 0
Sun Dec 13 20:17:14 2020: DEBUG     : lustre_client config() called
Sun Dec 13 20:17:14 2020: DEBUG     : msg_no 17 flags 3 rec_len 28 rsp_err 0
Sun Dec 13 20:17:14 2020: DEBUG     : msg_no 18 flags 3 rec_len 28 rsp_err 0
Sun Dec 13 20:17:14 2020: INFO      : Processing the config file '/opt/ovis/etc/ldms/sampler.conf' is done.
Sun Dec 13 20:17:14 2020: INFO      : Listening on sock:411 using `sock` transport and `none` authentication
Sun Dec 13 20:17:14 2020: INFO      : Enabling in-band config

Later we have logs:
Sun Dec 13 20:17:29 2020: DEBUG     : lustre_client llite_general_sample() sjtu-ffff9f6c91afe000
Sun Dec 13 20:17:30 2020: DEBUG     : lustre_client sample() called
Sun Dec 13 20:17:30 2020: DEBUG     : lustre_client llite_general_sample() scrfs-ffff9f847e2cc000
Sun Dec 13 20:17:30 2020: DEBUG     : lustre_client llite_general_sample() sjtu-ffff9f6c91afe000
Sun Dec 13 20:17:31 2020: DEBUG     : lustre_client sample() called
Sun Dec 13 20:17:31 2020: DEBUG     : lustre_client llite_general_sample() scrfs-ffff9f847e2cc000
Sun Dec 13 20:17:31 2020: DEBUG     : lustre_client llite_general_sample() sjtu-ffff9f6c91afe000
Sun Dec 13 20:17:32 2020: DEBUG     : lustre_client sample() called
Sun Dec 13 20:17:32 2020: DEBUG     : lustre_client llite_general_sample() scrfs-ffff9f847e2cc000
Sun Dec 13 20:17:32 2020: DEBUG     : lustre_client llite_general_sample() sjtu-ffff9f6c91afe000
Sun Dec 13 20:17:33 2020: DEBUG     : lustre_client sample() called
Sun Dec 13 20:17:33 2020: DEBUG     : lustre_client llite_general_sample() scrfs-ffff9f847e2cc000
Sun Dec 13 20:17:33 2020: DEBUG     : lustre_client llite_general_sample() sjtu-ffff9f6c91afe000
Sun Dec 13 20:17:34 2020: DEBUG     : lustre_client sample() called

The plugin seems to work, but with "ldms_ls -h localhost  -p 411", we could not see llnl plugins:
cas204/procstat
cas204/procnetdev
cas204/meminfo
cas204/loadavg

However if we copy the lib files made by default path over to alternative path, the plugin shows:
cas205/procstat
cas205/procnetdev
cas205/meminfo
cas205/loadavg
cas205.pi.sjtu.edu.cn/sjtu-ffff9f6c91afe000
cas205.pi.sjtu.edu.cn/scrfs-ffff9f847e2cc000

We have the following installation steps:
./bootstrap
mkdir build
cd build
../configure --prefix=/opt/ovis --with-libldms-prefix=/opt/ovis
make
make install

And the following configuration for llnl plugin:
load name=llnl_lustre_client
config name=llnl_lustre_client
start name=llnl_lustre_client interval=60000000

**Comment by morrone** [comment]
When you say "file installed by default path", I can only assume that was files left over from an older install of ldms-plugins-llnl. Since that set of plugins has has issue #4, it must be older than ldms-plugins-llnl 1.8.

I will add version information to the "get_plugin" debug message to make the version clearer in the future.

In the mean time, nothing immediately jumps out to me as the obvious problem. The main thing that probably changed from 1.8 to 1.11 in the actual plugin code is the addition of jobid fields. But I can't reproduce the problem yet, and I don't yet see how that might have caused this.

**Comment by morrone** [comment]
Wait, no I'm really confused. Issue #4 was a bug in llnl_lustre_ost, but this ticket is about the llnl_lustre_client. I don't understand how llnl_lustre_client could have issue #4.

**Comment by wooloo1121** [comment]
@morrone Yeah sorry we used files made from older version where issue #4 haven't been solved yet. Issue #4  is gone in 1.10 (since 1.8). That is just a reproduction of the "no data show up" problem, issue #4 was certainly a problem with the ost plugins. 

With 1.11, even installed on default path we still cannot see the plugins with ldms_ls.

**Comment by morrone** [comment]
It is almost like ldms_set_publish() and ldms_set_unpublish() are not being called. The only way that I can think that would happen is if the lmds-plugins-llnl package used an ldms.h from lmds 3 instead of ldms 4. I have updated ldms-plugins-llnl to require ldms_set_publish() and call the publish/unpublish functions unconditionally.

Please try ldms-plugins-llnl version 1.12: https://github.com/LLNL/ldms-plugins-llnl/releases/tag/1.12

That will at least tell us if we are on the right track, or if we need to look elsewhere.

**Comment by wooloo1121** [comment]
@morrone Thank you so much, the problem is gone in 1.12. 👍
