### ISSUE TITLE
The samplers do not clean up outdated data

### ISSUE THREAD

**Issue by wooloo1121** [LLNL/ldms-plugins-llnl#9]
Hi,

We notice that the job stats samplers do not clean up data of outdated jobs. Many jobs have been over for a long time but their data are still there with ldms_ls. I'm not sure if it caused the problem mentioned in #6, but the memory of sampler side is wasted for sure.

Thank you and look forward to your reply.

**Comment by morrone** [comment]
The sampler should display any data that appears in lustre's jobs_stats. The sampler plugin has no knowledge of when jobs start or end. The Lustre server has no knowledge of when a job begins or ends either. So the data in the job_stats file will remain for whatever cache time you have configured in Lustre.

Or are you saying that the sampler still shows data when there is not longer data in the lustre job_stats file?

**Comment by wooloo1121** [comment]
@morrone Thank you for the explanation. We checked and haven't seen any data presented by the samplers not in the lustre job stats file.
